/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class cara extends javax.swing.JFrame {

    /**
     * Creates new form cara
     */
    public cara() {
        initComponents();
        car.setText("1. Penyesuaian Metode dengan Lingkungan\n"
                + "Kelapa sawit di daerah gambut juga memerlukan sistem drainase yang baik untuk mencukupi kebutuhan airnya.\n"
                + "Hal ini berbeda dengan kelapa-kelapa sawit yang ditanam di lahan mineral yang tidak terlalu membutuhkan mineral Cu dan Fe.\n"
                + "\n"
                + "2. Penggunaan Alat Berteknologi Tinggi\n"
                + "peralatan mekanis mampu memberikan hasil yang lebih maksimal. Jadi sebagai seorang investor yang baik, Anda harus selalu\n"
                + "memperbaharui informasi tentang peralatan pertanian yang modern ini dan membelinya jika memang benar-benar diperlukan.\n"
                + "\n"
                
                + "3. Pengendalian Gulma secara Intensif\n"
                + "Gulma adalah tanaman pengganggu yang tumbuh di area lahan kelapa sawit. Adanya gulma akan mengurangi unsur hara yang tersimpan \n"
                + "di dalam tanah yang notabene sangat dibutuhkan oleh pohon sawit dalam mendukung pertumbuhannya\n"
                + "\n"
                + "4. Pemeberantasan Hama dan Penyakit\n"
                + "Pemberantasan yang tepat terhadap hama dan penyakit ini sejak dini mampu mempertahankan produktifitas pohon sawit yang Anda pelihara.\n"
                + "\n"
                + "5. Pemupukan dengan Jadwal dan Dosis yang Tepat\n"
                + "Pemupukan kelapa sawit tidak boleh dilakukan sembarangan. Pemupukan ini harus dikerjakan menurut jadwal yang telah disusun sebelumnya \n"
                + "dan menggunakan dosis yang tepat. Beberapa pupuk yang sering dipakai untuk pohon sawit antara lain urea, ZA, KCI, dolomit, TSP, dan borate.\n"
                + " Tak ketinggalan beberapa petani kerap pula memberikan pupuk berupa cuprum dan ferrit.\n"
                + "\n"
                + "6. Penunasan yang Diatur\n"
                + "Tujuan penunasan adalah untuk mempertahankan struktur pohon kelapa sawit, membersihkan tanaman, dan meningkatkan produktifitasnya. \n"
                + "Pegerjaan penunasan wajib disesuaikan terhadap umur dari tanaman tersebut.\n"
                + "\n"
                + "7. Prosedur Pemanenan yang Benar\n"
                + "Proses pemanenan buah kelapa sawit harus dilaksanakan dengan teknik yang benar. Jika salah, maka besar kemungkinan hal tersebut dapat menyebabkan \n"
                + "tanaman mengalami stres. Akibatnya pun dapat ditebak yaitu pohon sawit enggan mengeluarkan bunga lagi sebagai calon bakal buah.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        car = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        jLabel2.setBackground(new java.awt.Color(51, 255, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("                                                 Cara Perawatan Sawit");

        car.setEditable(false);
        car.setColumns(20);
        car.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        car.setForeground(new java.awt.Color(0, 102, 102));
        car.setRows(5);
        car.setText("\n");
        jScrollPane1.setViewportView(car);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setText("Back To Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose(); 
new beranda().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea car;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
